server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/leandrobarros_dev/microservice-repo
          search-paths: notification
          username: ${user}
          password: ${password}

